config/routes.rb
Pro::Application.routes.draw do

resources :users do
  collection  do 
    get 'login' 
    post 'process_login'
  end
  member do
    get 'logout'
  end
end

resources :posts

end

app/models/post.rb
class Post < ActiveRecord::Base

	has_many :user_posts
	has_many :users, through: :user_posts, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base

# email_regex = /A\([A-Z][a-z]+$\)z/
# username_regex= /A\([a-z][0-9]\)z/

validates :f_name, presence:  true, 
				   length: {:maximum => 50  }
validates :l_name, presence:  true ,
			   length: {:maximum => 50 }
validates :username, presence: true,
		  format:  {:with => /([a-z][0-9])*/},
			length: {:maximum => 50}
		#	uniqueness: {:case_sensitive => true}
validates :email, 	presence: true,
			  format: {:with => /([A-Z][a-z])*/ },
			  uniqueness: {:case_sensitive => false} 
validates :password, presence: { message:"Pleasse provide Password.."},
		         length: { :within => 6..40, message: "Password id too short... "}

has_many :user_posts
has_many :posts, through: :user_posts, dependent: :destroy

def custom_method
	puts "Hello World!"
end
end

app/models/user_post.rb
class UserPost < ActiveRecord::Base
	belongs_to :user
	belongs_to :post
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def authenticate
  #	binding.pry
  	if session[:logout].present?
  		session[:id] = nil
			session[:username] = nil || 0
			session[:password] = nil
			session[:logout] = false	
  	end

  	user = User.where(id: params[:id], username: session[:username], password: session[:password]).first
  	if user.present?
  		@current_user = user
  		true
  	else
  		redirect_to login_users_path, notice: "You are not authenticated person to view this page.."
  		false
  	end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def index
	end

	def create
		@post = Post.create(params[:post])
	end

	def new
		@post = Post.new
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_filter :authenticate, only: [:show]

def index
	@user = User.all 
end

def show
	@user = User.find(params[:id])
end 

def create
	@user = User.create( 
		f_name: params[:user][:f_name],
		l_name: params[:user][:l_name],
		username: params[:user][:username],
		email: params[:user][:email],
		password: params[:user][:password]
		)
	if @user.save
		redirect_to @user, notice: "Account has been successfully created"
	else
		render 'new'
	end
end

def new
	@user = User.new
end

def login
	session[:id] = nil
	@user = ''
end

def process_login
	username = params[:username]
	password = params[:password]
	session[:username] = username
	session[:password] = password
	user = User.where(username: username, password: password).first
	if user.present?
		session[:id] = user.id
		redirect_to user_path(session[:id])
	else
		redirect_to login_users_path, notice: "Please sign in with Valid Username or Password."
	end
end

def logout

	session[:logout] = true
	redirect_to action: "process_login" , notice: "You are successfully logout"
	#binding.pry
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pro</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
 <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "MY BLOG", '/users', id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home",   '/users' %></li>
            <li><%= link_to "Help",   '#' %></li>
            <li><%= link_to "Log in", '/users/login' %></li>
          </ul>
        </nav>
      </div>
    </header>
<div class="container">
      <%= yield %>
    </div>
</body>
</html>

app/views/posts/new.html.erb
<%= form_for @post do |f| %>
	<%= hidden_field_tag :user_id, '@current_user.id' %>
	<%= f.submit %>
<% end %>

app/views/users/index.html.erb
<div class="center jumbotron">
  <h1>Welcome to the Sample App</h1>

  <h2>
    This is the home page for the
    <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    sample application.
  </h2>

  <%= link_to "Sign up now!", '/users/new', class: "btn btn-lg btn-primary" %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails logo"),
            'http://rubyonrails.org/' %>


<% for i in 1..10 %>
	This is my <%= i %> app.
<% end %>

app/views/users/login.html.erb
<div class="form-group">
	<%= form_for @user, url: {controller: 'users', action: 'process_login', method: 'post'} do |f|%>

		<div class='form-group has-error'>
			<% if flash[:notice].present? %>
			<p class='control-label'><%= flash[:notice] %></p>
			<% end %>
		</div >
		<div class="container">
			<div class='row'>
				<div class='col-lg-12'>
					<h2>Login</h2>
				</div>
			</div>
			<div class='row'>
				<div class='col-xs-12'>
					<div class='row'>
				<div class='col-sm-3'>
					<div class='control' id='login'>
						<%= f.label :username, "Username", class: 'form'%>
						<%= f.text_field :username, class: "form-control"%><br>

						<%= f.label :password, "Password"%>
						<%= f.password_field :password, class: "form-control"%><br><br>
						<%= f.submit 'Login', class: 'btn btn-primary'%>
					</div>
							</div>
					</div>
				</div>
			</div>
		</div>
	<%end%>
</div>

app/views/users/new.html.erb
		<legend>Sign Up</legend>

			<% if @user.errors.present? %>
			<div>
				<p><%= @user.errors.messages[:password].first %></p>
			</div>
			<% end %>

			<%= form_for @user do |f| %>
	<%= f.label :f_name, "First Name"%>
					<%= f.text_field :f_name %>
				
			<br>

	<%= f.label :l_name, "Last Name"%>
					<%= f.text_field :l_name %>
				
			<br>

	<%= f.label :username, "User Name"%>
			
					<%= f.text_field :username %>
				
			<br>

	<%= f.label :email, "Email"%>
			
					<%= f.text_field :email %>
				
	
			<br>

	<%= f.label :password, "Password"%></label>
			
					<%= f.password_field :password %>
				

			<br>

	

<br>
	
			<%= f.submit 'Sign Up'%>
		
			<%= f.submit 'Clear Form', type: 'reset' %>
		
<%end%>

app/views/users/show.html.erb
<h1>Welcome <%= @user.f_name %></h1>
<p>Your username is: <%= @user.username %></p>
<h2>You was being created on: <%= @user.created_at %></h2>


<a href= "<%= users_path %>" > Home</a>
<a href="<%= logout_user_path(@user.id) %>">LOGOUT </a>